# services:
#   postgres:
#     container_name: postgres
#     image: postgres
#     restart: always
#     environment:
#       POSTGRES_DB: taskbd
#       POSTGRES_USER: postgres
#       POSTGRES_PASSWORD: 123
#       ports:
#         - 5432:5432
#       volumes:
#         - postgres-data:/var/lib/postgresql/data
# volumes:
#   postgres-data:

version: '3.5'

services:
  db_auth:
    container_name: db_auth
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123
    image: postgres:14.3-alpine